# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lengthSeconds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
